language: php

sudo: false

php:
  - '7.0'
#  - '7.1'
#  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 -n src tests
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter