language: php

sudo: false

php:
  - '7.0'
#  - '7.1'
#  - nightly

before_install:
  - composer self-update
  - composer clear-cache

script:
  - vendor/bin/phpcs --standard=PSR2 -n src tests
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)