language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.0'
#  - '7.1'
#  - nightly


before_install:
  - composer --no-interaction global require hirak/prestissimo

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpcs --standard=PSR2 -n src tests
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
